name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check_analyzers:
      name: Check analyzers for ni.datastore
      uses: ./.github/workflows/check_ni_datastore.yml
  check_examples:
      name: Check analyzers for examples
      uses: ./.github/workflows/check_examples.yml
  check_utilities:
      name: Check analyzers for utilities
      uses: ./.github/workflows/check_utilities.yml
  check_docs:
    name: Check docs for ni.datastore
    uses: ./.github/workflows/check_docs.yml
  checks_succeeded:
      name: Checks succeeded
      needs: [check_analyzers, check_examples, check_docs]
      runs-on: ubuntu-latest
      steps:
        - run: exit 0
  run_unit_tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.10', 3.11, 3.12, 3.13, 3.14]
    name: Run unit tests
    uses: ./.github/workflows/run_unit_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
  tests_succeeded:
    name: Unit tests succeeded
    needs: [run_unit_tests]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
